apiVersion: v1
kind: Pod
metadata:
  name: ubuntu1
  labels:
    app: ubuntu
spec:
  containers:
  - image: ubuntu
    command:
      - "apt update && apt install curl iputils-ping nmap ufw -y"
    imagePullPolicy: IfNotPresent
    name: ubuntu1
  restartPolicy: Always
