apiVersion: v1
kind: Pod
metadata:
  name: ubuntu1
  labels:
    app: ubuntu
spec:
  containers:
  - image: ubuntu
    command: 
      - /bin/sh
      - -c
      - |
        "apt update"
        "apt install curl iputils-ping nmap cfw -y"
    imagePullPolicy: IfNotPresent
    name: ubuntu1
    ports:
    - containerPort: 3000
  restartPolicy: Always
