apiVersion: v1
kind: Pod
metadata:
  name: ubuntu1
  labels:
    app: ubuntu
spec:
  containers:
  - image: busybox
    command:
      - "sleep"
      - "604800"
    imagePullPolicy: IfNotPresent
    name: ubuntu1
    ports:
    - containerPort: 3000
  restartPolicy: Always
